$ErrorActionPreference = "Stop"

Write-Host '#!/usr/bin/env bash
# This file is autogenerated by lab/permanent-scripts/pack. Usage:
# script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash

TARGET_DIR=${TARGET_DIR:-/usr/local/bin}
'

function EscapeFile2Echo
{
    param([System.String] $fileName)

    $ret = ""
    $lines = [System.IO.File]::ReadAllLines($fileName)
   	$nameOnly=[System.IO.Path]::GetFileNameWithoutExtension($fileName)

    foreach ($line in $lines)
    {
        foreach ($c in $line.ToCharArray())
        {
            $ic=[int]$c;
            if ( $ic -eq 96 -or $ic -eq 34 -or $ic -eq 92 -or $ic -eq 36)
            {
                $ret = [System.String]::Concat(@($ret, "\", $c.ToString()))
            }
            elseif ($ic -ge 32)
            {
                $ret = [System.String]::Concat(@($ret, $c.ToString()))
            }
            else
            {
                $ret = [System.String]::Concat(@($ret, "\x", [string]::Format("{0:X2}", [int]$c)))
            }
        }
        $ret = [System.String]::Concat(@($ret, [Environment]::NewLine))
    }
    return $ret
}

function WriteFile
{
    param([System.String] $fileName)

   	$nameOnly=[System.IO.Path]::GetFileNameWithoutExtension($fileName)
    $escaped = EscapeFile2Echo $fileName
    $nl=[Environment]::NewLine
    $escaped_and_Queted="`"$($escaped)$($nl)`""
    $ret = "# $($nameOnly)
echo -e $($escaped_and_Queted) > `${TARGET_DIR}/$($nameOnly) 2>/dev/null ||
echo -e $($escaped_and_Queted) | sudo tee `${TARGET_DIR}/$($nameOnly) >/dev/null;
if [[ -f `${TARGET_DIR}/$($nameOnly) ]]; then 
    chmod +x `${TARGET_DIR}/$($nameOnly) >/dev/null 2>&1 || sudo chmod +x `${TARGET_DIR}/$($nameOnly)
	echo `"OK: `${TARGET_DIR}/$($nameOnly)`"; 
else `"Error: Unable to extract `${TARGET_DIR}/$($nameOnly)`"; fi
"

	return $ret
}
 

Get-ChildItem -Path ../ -Filter *.sh -File | ForEach-Object {
    $_.FullName
} | ForEach-Object {
	$nameOnly=[System.IO.Path]::GetFileNameWithoutExtension($_)
	$content=Get-Content "$_"
	"$(WriteFile $_)"
}
