language: shell
os: linux
dist: bionic # xenial's qemu is too old
git:
  depth: false

matrix:
  include:
    - env: [ARCH=i386]
    - env: [ARCH=arm]
    - env: [ARCH=arm64]

    # https://docs.travis-ci.com/user/caching/ (nothing to cache)
before_script:
- 'echo ARCH: $ARCH'
- | 
  sudo apt update; 
  sudo apt install -y libguestfs-tools sshpass sshfs qemu-system-arm qemu-block-extra qemu-utils p7zip-full \
    libguestfs-tools qemu-system-arm qemu-system-i386 \
    qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
  
  apt clean
  
  sudo modprobe kvm
  kvm-ok
  bash install-mono.sh
  
- |
    url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-dependencies.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) | bash
    script=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash -s pwsh

script:
- sudo mkdir -p /transient-builds/test-and-build
- sudo chown -R travis:travis /transient-builds
- | 
  if [[ "$ARCH" == "i386" ]]; then
    # on i386 we skip nodejs only
    export Ignore_Features="nodejs" 
  else
    # on arm/arm64 we install nothing only 
    export PreInstall_Only_Features="nothing"
  fi
- sudo pwsh -command ./image-builder.ps1 -Images $ARCH -Only \"$PreInstall_Only_Features\" -Skip \"$Ignore_Features\"
- cat Private-Report/*/*onfinish*
- 'pushd Private-Report; find .; popd'
- cat Private-Report/*/$ARCH-said-by-user.log
- cat Private-Report/*/$ARCH-said-by-root.log
