language: shell
os: linux
dist: bionic # xenial's qemu is too old
git:
  depth: false

matrix:
  include:
    - env: [ARCH=i386]
    - env: [ARCH=arm]
    - env: [ARCH=arm64]

    # https://docs.travis-ci.com/user/caching/ (nothing to cache)
before_script:
- 'echo ARCH: $ARCH'
- | 
  sudo apt update; 
  sudo apt install -y libguestfs-tools sshpass sshfs qemu-system-arm qemu-block-extra qemu-utils p7zip-full \
    libguestfs-tools qemu-system-arm qemu-system-i386 \
    qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
  
  apt clean
  
  sudo modprobe kvm
  kvm-ok
  
- |
    url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-dependencies.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) | bash
    script=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash -s pwsh

script:
- sudo pwsh -command ./image-builder.ps1 -Images $ARCH
- cat Public-Report/*onfinish*
- ls -la Public-Report
- cat Public-Report/$ARCH-said-by-user.log
- cat Public-Report/$ARCH-said-by-root.log