# https://aka.ms/yaml
jobs:
  - job: ARM32_V7
    variables:
      ARCH: arm
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps.yml  # Template reference

  - job: ARM64_V8
    variables:
      ARCH: arm64
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps.yml  # Template reference


trigger:
- master


