# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: uname -a 
    displayName: 'show kernel version'

  - script: df -h
    displayName: 'show disk free space'

  - script: sudo du / -d 2 -h || true
    displayName: 'show disk usage'

  - script: sudo lscpu
    displayName: 'show cpu'

  - script: free -m; sudo swapon
    displayName: 'show memory usage'


  - script: 7z b
    displayName: '7z benchmark'

  - script: |
      path="/transient-builds"
      file="/mnt/BTRFS.disk"
      time sudo apt-get install btrfs-tools -y -qq
      sudo dd if=/dev/zero of="/$file" bs=1 seek=10900M count=1
      sudo mkfs.btrfs -L a-disk "$file"
      sudo mkdir -p "$path"
      sudo mount -t btrfs "$file" "$path" -o defaults,noatime,nodiratime,compress-force=zlib,norecovery
      df -h

      
    displayName: 'prepare /transient-builds'

  - script: |
      sudo apt-get update -yqq
      command -v gem || (sudo apt-get install -y ruby-dev; sudo gem install dpl)

    displayName: 'install dpl using sudo'

  - script: |
        sudo apt update;
        sudo apt install -y libguestfs-tools sshpass sshfs qemu-system-arm qemu-block-extra qemu-utils p7zip-full \
        libguestfs-tools qemu-system-arm qemu-system-i386 \
        qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker

        sudo apt clean

        sudo modprobe kvm
        sudo kvm-ok
        ls -la /dev/kvm
        true

    displayName: 'pre-install qemu'


#- script: |
#        echo "IAM $(whoami)"
#        uname -a
#        cat /etc/os-release
#        cat /etc/*release
#        docker version || true
#        dotnet --info || true
#        mono --version || true
#    
#  displayName: 'Run a multi-line script'
