# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
strategy:
  matrix:
    ARM32_V7:
      arch: 'arm'
    ARM64_V8:
      arch: 'arm64'

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: uname -a
    displayName: 'show kernel version'

  - script: 'printenv | sort'
    displayName: 'show environment'

  - script: df -T -h
    displayName: 'show disk free space'

  - script: |
      sudo fdisk -l
      # 14334.9 Mb
      time sudo apt-get install btrfs-tools -y -qq
      path="/transient-builds"
      sudo mkdir -p "$path"
      
      if [ true ]; then
          sudo umount /mnt
          file=/dev/sdb1
      else
          file="/mnt/BTRFS.disk"
          sudo dd if=/dev/zero of="/$file" bs=1 seek=12800M count=1
      fi
      
      sudo mkfs.btrfs -f -L a-disk "$file" -O ^extref,^skinny-metadata
      echo "MOUNTING $file as $path"
      sudo mount -t btrfs "$file" "$path" -o defaults,noatime,nodiratime,compress-force
      sudo chown $(whoami) $path
      touch $path/hi
      df -T -h

    displayName: 'prepare /transient-builds'

  - script: sudo lscpu
    displayName: 'show cpu'

  - script: free -m; sudo swapon
    displayName: 'show memory usage'


  - script: 7z b
    displayName: '7z benchmark'


  - script: |
      sudo apt-get update -yqq
      command -v gem || (sudo apt-get install -y ruby-dev; sudo gem install dpl)

    displayName: 'install dpl using sudo'

  - script: |
        sudo apt update;
        sudo apt install -y libguestfs-tools sshpass sshfs qemu-system-arm qemu-block-extra qemu-utils p7zip-full \
        libguestfs-tools qemu-system-arm qemu-system-i386 \
        qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker

        sudo apt clean

        sudo modprobe kvm
        sudo kvm-ok
        ls -la /dev/kvm
        true

    displayName: 'pre-install qemu'

  - script: sudo du / -d 2 -h || true
    displayName: 'show disk usage'

#- script: |
#        echo "IAM $(whoami)"
#        uname -a
#        cat /etc/os-release
#        cat /etc/*release
#        docker version || true
#        dotnet --info || true
#        mono --version || true
#    
#  displayName: 'Run a multi-line script'
